
{

gROOT->ProcessLine(".L optimusPrime.cxx+");
gROOT->ProcessLine(".L fqProcessedEvent.cxx+");
gROOT->ProcessLine(".L mcLargeArray.cxx+");
gROOT->ProcessLine(".L TH2FV.cxx+");
gROOT->ProcessLine(".L summaryPlots.cxx+");
gROOT->ProcessLine(".L moreUncertainties.cxx+");
gROOT->ProcessLine(".x ~/style.c");
gStyle->SetPalette(53);
gStyle->SetOptTitle(1);

///////////////////////////////////////////////////////////////////////////
// parameters /////////////////////////////////////////////////////////////

// file names of processed T2K MC
TString T2KMCFiles = "/nfs/data41/t2k/amissert/t2kmc/processed/feb23pass_1rpi/*.root";

// card file name for other settings
TString CardFileName = "wetrun.dat";

// directory to find additional uncertainty files (entering bg, etc)
TString DataFileDirectory = "/nfs/data41/t2k/amissert/atmos/head/atmFitTools/data/";
// names of uncertainty maps
TString  UncMapFileNameNuE = "official/FVUncMapNuE.root";
TString  UncMapFileNameNuMu = "official/FVUncMapNuMu.root";
TString  UncMapFileNameNuE1RPi = "official/FVUncMapNuE1RPi.root";

// name of uncertainty map file generated by toy MC
TString UncertaintyMapFile = "FVUncMapNuMu.root";

// max # of events to use
int     NMaxMCEvents = 2e9;
//int     NMaxMCEvents = 100000;
int IndexPIDPar = 0;
int IndexPi0Par = 1;
int IndexPiPPar = 2;
int IndexRCPar = 3;
//////////////////////////////////////////////////////////////////////////////


// chain setup
TChain ch("h1");
ch.Add(T2KMCFiles.Data());

// optimizer setup
optimusPrime* opt = new optimusPrime(&ch,NMaxMCEvents,DataFileDirectory.Data(),
                                                      UncMapFileNameNuE.Data(),
                                                      UncMapFileNameNuMu.Data(),
                                                      UncMapFileNameNuE1RPi.Data());
opt->cardFileName = CardFileName.Data();
opt->indexPIDPar = IndexPIDPar;
opt->indexPi0Par = IndexPi0Par;
opt->indexPiPPar = IndexPiPPar;
opt->indexRCPar = IndexRCPar;

//opt->calcFOMMap(350,350,0,30,2);
// optimization metric
/*  
opt->FOMType = 2;
opt->calcFOMMap(350,350,3,30,1);
cc->Print("~/transfer/fom_nue.png");
opt->calcFOMMap(350,350,3,30,3);
cc->Print("~/transfer/fom_nue1rpi.png");
opt->calcFOMMap(350,350,0,30,2);
cc->Print("~/transfer/fom_numu.png");
// power density
opt->FOMType = 2;
opt->calcFOMMap(350,350,3,30,1);
cc->Print("~/transfer/fom_power_den_nue.png");
opt->calcFOMMap(350,350,3,30,3);
cc->Print("~/transfer/fom_power_den_nue1rpi.png");
opt->calcFOMMap(350,350,0,30,2);
cc->Print("~/transfer/fom_power_den_numu.png");
*/
// sys density
opt->FOMType = 4;
opt->calcFOMMap(350,350,3,30,1);
cc->Print("~/transfer/fom_sys_den_nue.png");
opt->calcFOMMap(350,350,3,30,3);
cc->Print("~/transfer/fom_sys_den_nue1rpi.png");
opt->calcFOMMap(350,350,0,30,2);
cc->Print("~/transfer/fom_sys_den_numu.png");
// nev densityi /*  
/*  
opt->FOMType = 3;
opt->calcFOMMap(350,350,3,30,1);
cc->Print("~/transfer/fom_nev_nue.png");
opt->calcFOMMap(350,350,3,30,3);
cc->Print("~/transfer/fom_nev_nue1rpi.png");
opt->calcFOMMap(350,350,0,30,2);
cc->Print("~/transfer/fom_nev_numu.png");
*/
}


